### PR TITLE
Fixed standard deviation formula to use percentage change

### PR DESCRIPTION
**Pull request by summatix**

### CODE REVIEW

**Comment by summatix** [comment]
For reference, here is the fixed formula
image

**Comment by lokdao** [comment]
Are we not changing the description of x 
from `x is the set of the iAsset’s tracked asset’s historical daily close price for the past year` 
to `x is the set of the iAsset’s tracked asset’s historical daily close price percentage change for the past year` ?

**Comment by TheLapinMalin** [comment]
> No, it makes more sense to update the math than to update the text

But then, I feel like the formula is incorrect.

You're computing the average change, and subtracting the mean value of x from it? The units don't match as far as I can tell.

**Comment by summatix** [comment]
Fixed in #5

**Pull request closed without merging**
